version: '3'
services:
  # Go application service
  db:
    container_name: db
    image: postgres:alpine
    environment:
      POSTGRES_DB: recipe
      POSTGRES_USER: root
      POSTGRES_PASSWORD: kaak
    ports:
    - 5432:5432
    networks:
      - recipenet
    volumes: 
      - ./internal/db/migration/000001_recipe.up.sql:/docker-entrypoint-initdb.d/000001_recipe.up.sql
      - ./internal/db/migration/000002_user.up.sql:/docker-entrypoint-initdb.d/000002_user.up.sql
      - ./internal/db/migration/recipes_202304170548.sql:/docker-entrypoint-initdb.d/recipes_202304170548.sql
      - ./internal/db/migration/users_202304170552.sql:/docker-entrypoint-initdb.d/users_202304170552.sql
  app:
    container_name: app
    build: .
    env_file:
      - .env
    ports:
      - 8000:8000
    networks:
      - recipenet
    depends_on:
      - db
    links:
      - db
      
networks:
  recipenet:
    driver: bridge
volumes:
  postgres-db: